#!/usr/bin/env bash
# Builds the Linux packages for one target: .deb, .rpm and an AppImage, each
# with a .sha256 next to it, in dist/.
#
#   scripts/package/linux.sh <target> [version] [formats]
#
# `formats` is a comma-separated subset of deb,rpm,appimage (default: all).
# The binary and the notices come from the release archive's staging folder,
# so every package ships exactly what the archive ships (built with FEATURES,
# default "jack"). Needs cargo-deb and cargo-generate-rpm; the AppImage
# needs appimagetool (downloaded into dist/staging/tools if missing).
set -euo pipefail

target="${1:?usage: linux.sh <target> [version] [formats]}"
root="$(cd "$(dirname "$0")/../.." && pwd)"
version="${2:-$(sed -n 's/^version = "\(.*\)"$/\1/p' "${root}/Cargo.toml" | head -n1)}"
formats="${3:-deb,rpm,appimage}"
export FEATURES="${FEATURES-jack}"
dist="${root}/dist"
stage="${dist}/fauste-player-${version}-${target}"
work="${root}/dist/staging"
app_id="org.fauste.FaustePlayer"

want() { [[ ",${formats}," == *",$1,"* ]]; }

checksum() {
  (cd "$(dirname "$1")" && sha256sum "$(basename "$1")" > "$(basename "$1").sha256")
}

# 1. The release archive's contents (binary, notices). Always rebuilt (a
# no-op when nothing changed), so a package never ships a stale binary or
# one built with other features.
"${root}/scripts/package-release.sh" "${target}" "${version}" >/dev/null
mkdir -p "${work}"
"${root}/scripts/package/metainfo.sh" "${version}" "${work}/${app_id}.metainfo.xml"
if [ -f "${stage}/licenses/THIRD-PARTY.html" ]; then
  cp "${stage}/licenses/THIRD-PARTY.html" "${work}/THIRD-PARTY.html"
else
  echo "<p>Third-party notices are generated by cargo-about in release builds.</p>" \
    > "${work}/THIRD-PARTY.html"
fi

# 2. Debian package.
if want deb; then
  # A SemVer pre-release (0.2.0-rc.1) sorts before its release with `~`.
  deb="$(cd "${root}" && cargo deb -p fp-app --no-build --no-strip --target "${target}" \
    --deb-version "${version//-/\~}" -o "${dist}/" | tail -n1)"
  checksum "${deb}"
  echo "${deb}"
fi

# 3. RPM package.
if want rpm; then
  rpm_version="${version//-/\~}"
  (cd "${root}" && cargo generate-rpm -p crates/fp-app --target "${target}" \
    --set-metadata "version = \"${rpm_version}\"" -o "${dist}/")
  rpm="$(ls -t "${dist}"/fauste-player-*"${rpm_version}"*.rpm | head -n1)"
  checksum "${rpm}"
  echo "${rpm}"
fi

# 4. AppImage.
if want appimage; then
  case "${target}" in
    x86_64-*) arch=x86_64 ;;
    aarch64-*) arch=aarch64 ;;
    *) echo "no AppImage for ${target}" >&2; exit 1 ;;
  esac
  tool="${APPIMAGETOOL:-$(command -v appimagetool || true)}"
  if [ -z "${tool}" ]; then
    # A fixed release, checked against its SHA-256 before it runs.
    appimagetool_version=1.9.1
    case "$(uname -m)" in
      x86_64) appimagetool_sha256=ed4ce84f0d9caff66f50bcca6ff6f35aae54ce8135408b3fa33abfc3cb384eb0 ;;
      aarch64) appimagetool_sha256=f0837e7448a0c1e4e650a93bb3e85802546e60654ef287576f46c71c126a9158 ;;
      *) echo "no appimagetool for $(uname -m)" >&2; exit 1 ;;
    esac
    tool="${work}/tools/appimagetool-${appimagetool_version}-$(uname -m).AppImage"
    if [ ! -x "${tool}" ]; then
      mkdir -p "${work}/tools"
      curl -fsSL -o "${tool}.part" \
        "https://github.com/AppImage/appimagetool/releases/download/${appimagetool_version}/appimagetool-$(uname -m).AppImage"
      echo "${appimagetool_sha256}  ${tool}.part" | sha256sum -c - >&2
      mv "${tool}.part" "${tool}"
      chmod +x "${tool}"
    fi
  fi
  appdir="${work}/${target}/AppDir"
  rm -rf "${appdir}"
  mkdir -p "${appdir}/usr/bin" "${appdir}/usr/share/applications" \
    "${appdir}/usr/share/metainfo" "${appdir}/usr/share/doc/fauste-player"
  cp "${stage}/fauste-player" "${appdir}/usr/bin/"
  cp "${root}/packaging/linux/${app_id}.desktop" "${appdir}/usr/share/applications/"
  cp "${root}/packaging/linux/${app_id}.desktop" "${appdir}/"
  cp "${work}/${app_id}.metainfo.xml" "${appdir}/usr/share/metainfo/${app_id}.appdata.xml"
  for n in 16 32 48 64 128 256 512; do
    mkdir -p "${appdir}/usr/share/icons/hicolor/${n}x${n}/apps"
    cp "${root}/packaging/icons/fauste-player-${n}.png" \
      "${appdir}/usr/share/icons/hicolor/${n}x${n}/apps/${app_id}.png"
  done
  cp "${root}/packaging/icons/fauste-player-256.png" "${appdir}/${app_id}.png"
  cp -r "${stage}/licenses/." "${appdir}/usr/share/doc/fauste-player/"
  cat > "${appdir}/AppRun" <<'RUN'
#!/bin/sh
here="$(dirname "$(readlink -f "$0")")"
exec "${here}/usr/bin/fauste-player" "$@"
RUN
  chmod +x "${appdir}/AppRun"
  image="${dist}/fauste-player-${version}-${arch}.AppImage"
  # The tool is itself an AppImage: extract-and-run avoids needing FUSE.
  ARCH="${arch}" APPIMAGE_EXTRACT_AND_RUN=1 "${tool}" --no-appstream "${appdir}" "${image}" >/dev/null
  "${image}" --appimage-extract-and-run --version
  checksum "${image}"
  echo "${image}"
fi
