#!/usr/bin/env bash
# Builds the Windows installer (.msi) for one target, with a .sha256, in
# dist/. Runs in Git Bash on Windows; needs cargo-wix and the WiX Toolset v3.
#
#   scripts/package/windows.sh <target> [version]
#
# When WINDOWS_CERT_PFX (base64 of a .pfx) and WINDOWS_CERT_PASSWORD are set,
# the executable and the installer are signed with signtool and timestamped;
# otherwise both stay unsigned (SmartScreen then asks before running them).
set -euo pipefail

target="${1:?usage: windows.sh <target> [version]}"
root="$(cd "$(dirname "$0")/../.." && pwd)"
version="${2:-$(sed -n 's/^version = "\(.*\)"$/\1/p' "${root}/Cargo.toml" | head -n1)}"
export FEATURES="${FEATURES-jack}"
dist="${root}/dist"
stage="${dist}/fauste-player-${version}-${target}"
work="${dist}/staging"
exe="${root}/target/${target}/release/fauste-player.exe"

if [ ! -f "${stage}/fauste-player.exe" ]; then
  "${root}/scripts/package-release.sh" "${target}" "${version}" >/dev/null
fi
mkdir -p "${work}"
cp "${stage}/licenses/THIRD-PARTY.html" "${work}/THIRD-PARTY.html" 2>/dev/null \
  || echo "<p>Third-party notices are generated by cargo-about in release builds.</p>" \
    > "${work}/THIRD-PARTY.html"

signtool_path() {
  command -v signtool 2>/dev/null && return
  ls "/c/Program Files (x86)/Windows Kits/10/bin/"*/x64/signtool.exe 2>/dev/null | sort | tail -n1
}

sign() {
  [ -n "${WINDOWS_CERT_PFX:-}" ] || return 0
  local tool pfx
  tool="$(signtool_path)"
  pfx="${work}/signing.pfx"
  printf '%s' "${WINDOWS_CERT_PFX}" | base64 -d > "${pfx}"
  "${tool}" sign /f "${pfx}" /p "${WINDOWS_CERT_PASSWORD:-}" /fd SHA256 \
    /tr http://timestamp.digicert.com /td SHA256 "$1"
  rm -f "${pfx}"
}

sign "${exe}"
msi="${dist}/fauste-player-${version}-${target}.msi"
(cd "${root}" && cargo wix -p fp-app --no-build --nocapture --target "${target}" \
  --include packaging/windows/main.wxs --install-version "${version}" --output "${msi}")
sign "${msi}"
(cd "${dist}" && sha256sum "$(basename "${msi}")" > "$(basename "${msi}").sha256")
echo "${msi}"
