[package]
name = "fp-remote"
description = "Remote control over the network: HTTP/JSON API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
fp-model.workspace = true
arc-swap.workspace = true
axum.workspace = true
tokio.workspace = true
futures-util.workspace = true
rosc.workspace = true
tower.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
http-body-util.workspace = true

[lints]
workspace = true
